// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by kf-gen package

pub mod klocalization;
pub use klocalization::setupLocalizedContext;
