// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by kf-gen package

fn get_non_generic_types() -> [QtNonGenericType; 0usize] {
    []
}
fn get_generic_types() -> [QtGenericTypeWithoutArgs; 0usize] {
    []
}
fn get_monomorphed_types() -> [QtMonomorphedType; 0usize] {
    []
}
fn get_alias_to_monomorphed_types() -> [QtAliasToMonomorphedType; 0usize] {
    []
}
